version: 0.2

phases:
 install:
  commands:
   - npm ci

  pre_build:
   commands:
    - aws s3 rm s3://auth-app-front --recursive
 build:
  commands:
   - npm run build

artifacts:
 files:
  - build/**/*
